app:
  image: docker_pie
  environment:
    SERVICE_80_NAME: http
    SERVICE_NAME: app
    SERVICE_TAGS: production
  ports:
  - "80"
lb:
  build: ./
  links:
  - consul
  ports:
  - "80:80"
  
consul:
  command: -bootstrap
  image: gliderlabs/consul-server:latest
  ports:
  - "8300:8300"
  - "8400:8400"
  - "8500:8500"
  - "8600:53/udp"


registrator:
  command: consul://192.168.99.100:8500
  image: gliderlabs/registrator:latest
  links:
  - consul
  volumes:
  - "/var/run/docker.sock:/tmp/docker.sock"
